compile fixes
fixes

/home/chris/build/osvr-vive-github/Properties.h:71:7: error: 'vector' in namespace 'std' does not name a template type
  std::vector<PropertiesStore *> m_propertyStores;
       ^~~~~~

and

In file included from /usr/include/boost/type_index/stl_type_index.hpp:32:0,
                 from /usr/include/boost/type_index.hpp:29,
                 from /usr/include/boost/variant/variant.hpp:21,
                 from /usr/include/boost/variant.hpp:17,
                 from /home/chris/build/osvr-vive-github/vendor/util-headers/util/KVDataStore.h:35,
                 from /home/chris/build/osvr-vive-github/Properties.h:31,
                 from /home/chris/build/osvr-vive-github/Properties.cpp:26:
/usr/include/boost/variant/get.hpp: In instantiation of 'typename boost::add_reference<const U>::type boost::strict_get(const boost::variant<T0, TN ...>&) [with U = float*; T0 = bool; TN = {float, int, long unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; typename boost::add_reference<const U>::type = float* const&]':
/usr/include/boost/variant/get.hpp:307:25:   required from 'typename boost::add_reference<const U>::type boost::get(const boost::variant<T0, TN ...>&) [with U = float*; T0 = bool; TN = {float, int, long unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; typename boost::add_reference<const U>::type = float* const&]'
/home/chris/build/osvr-vive-github/vendor/util-headers/util/KVDataStore.h:69:42:   required from 'bool osvr::util::KVDataStore<KeyType, ValueVariant>::contains(const key_type&) const [with T = float; KeyType = vr::ETrackedDeviceProperty; ValueVariant = boost::variant<bool, float, int, long unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >; osvr::util::KVDataStore<KeyType, ValueVariant>::key_type = vr::ETrackedDeviceProperty]'
/home/chris/build/osvr-vive-github/vendor/util-headers/util/KVDataStore.h:78:29:   required from 'T osvr::util::KVDataStore<KeyType, ValueVariant>::get(const key_type&) const [with T = float; KeyType = vr::ETrackedDeviceProperty; ValueVariant = boost::variant<bool, float, int, long unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >; osvr::util::KVDataStore<KeyType, ValueVariant>::key_type = vr::ETrackedDeviceProperty]'
/home/chris/build/osvr-vive-github/Properties.cpp:53:52:   required from here
/usr/include/boost/variant/get.hpp:237:5: error: static assertion failed: boost::variant does not contain specified type U, call to boost::get<U>(const boost::variant<T...>&) will always throw boost::bad_get exception
     BOOST_STATIC_ASSERT_MSG(
     ^